name: GitHub Actions CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test1:
    name: compute, satellite-proxy, canary, runner
    runs-on: ubuntu-latest
    env:
      EARTHLY_TOKEN: "${{ secrets.EARTHLY_TOKEN }}"
      EARTHLY_ORG: "earthly-technologies"
      GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: test
        run: |-
          which git  && \
          git status